=== pedroduarte870/BerliozManager/back_end/Communication/export/audition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="auditions">
        <xs:complexType>
            <xs:sequence maxOccurs="1">
                <xs:element maxOccurs="unbounded" name="audition">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1">
                            <xs:element name="metadata">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="subtitle" type="xs:string"/>
                                        <xs:element name="subject" type="xs:string"/>
                                        <xs:element name="organizer" type="xs:string"/>
                                        <xs:element name="place" type="xs:string"/>
                                        <xs:element name="date" type="xs:string"/>
                                        <xs:element name="time" type="xs:string"/>
                                        <xs:element name="duration" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="performances">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="performance">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="1">
                                                  <xs:element minOccurs="0" name="group"
                                                  type="xs:string"/>
                                                  <xs:element name="leaders">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="1">
                                                  <xs:element maxOccurs="unbounded" name="leader"
                                                  type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="performers">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="1">
                                                  <xs:element maxOccurs="unbounded" name="performer"
                                                  type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="plays">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="1">
                                                  <xs:element maxOccurs="unbounded" name="play"
                                                  type="xs:string"> </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pedroduarte870/BerliozManager/back_end/Communication/export/xml/audition1.xml
<?xml version="1.0" encoding="UTF-8"?>
<auditions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="/var/www/html/BerliozManager/back_end/export/audition.xsd">
    <audition>
        <metadata>
            <title>Audição de Cordas</title>
            <subtitle>Avaliação dos alunos de cordas</subtitle>
            <subject>Cordas</subject>
            <organizer>Joaquim de Almeida</organizer>
            <place>Auditório A4</place>
            <date>01/03/2016</date>
            <time>14h00</time>
            <duration>2h</duration>
        </metadata>
        <performances>
            <performance>
                <group>Grupo de Cordas</group>
                <leaders>
                    <leader>ALVARO ZÉ DE CASTRO MOREIRA DA SILVA</leader>
                    <leader>PEDRO MANUEL VIEIRA SANTOS PINTO</leader>
                </leaders>
                <performers>
                    <performer>Eusébio da Silva Ferreira</performer>
                </performers>
                <plays>
                    <play>Funeral March in Memory of Rikard Nordraak</play>
                    <play>Singet dem Herrn ein neues Lied</play>
                </plays>
            </performance>    
        </performances>
    </audition>    
</auditions>

=== pedroduarte870/BerliozManager/back_end/Communication/export/auditions.xml
<?xml version="1.0" encoding="UTF-8"?>
<auditions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/pedroduarte/%C3%81rea%20de%20Trabalho/audition.xsd">
    <audition>
        <metadata>
            <title></title>
            <subtitle></subtitle>
            <subject></subject>
            <organizer></organizer>
            <place></place>
            <date></date>
            <time></time>
            <duration></duration>
        </metadata>
        <performances>
            <performance>
                <leaders>
                    <leader></leader>
                </leaders>
                <performers>
                    <performer></performer>
                </performers>
                <plays>
                    <play></play>
                </plays>
            </performance>
        </performances>
    </audition>
</auditions>
